### ISSUE TITLE
Cryptominer built into website used as demo

### ISSUE THREAD

**Issue by shiftctrl-io** [JosiahLeas/josiahleas.github.io#39]
Don't click the site to view the demo - it's using your computer/browser to mine coins

**Comment by shellstrom** [comment]
Please elaborate.

The title "Cryptominer built into website used as demo". What do you mean by "demo"?
The phrase "Don't click the site to view the demo". What do you mean by "view the demo"?


The miner is supposed to be used as a way for visitors who'd like to donate cryptos through mining, to the site developers.
The miner never starts itself. You have to go to the Help/Donate section and click the "Start mining" button to allow the miner to start, which makes this an active choice.

What is it that you'd like to see fixed by this issue?

**Comment by shiftctrl-io** [comment]
As I was trying to view the demo, the miner self activated without clicking any "start mining" button. I killed the process and exited.

**Comment by shellstrom** [comment]
Very sorry to hear that.

But what is this "demo" you are referring to?

We have had this _opt-in_ miner implemented for more than 2 weeks and you are the first to report an issue with having started mining on its own.

What browser and version are you using? Have you tried to go to the website after
* having cleaned all your cookies
* disabled extensions 
* using it in a private session?

We haven't so far been able to repeat this situation you have reported. Please share more details on your environments and steps on how you can repeat this behaviour, in order for us to be able to investigate this issuu and give it the attention it needs.

**Comment by P-Medicado** [comment]
The miner, we have removed it. @shellstrom is exactly right, we have never had a miner forcibly or automatically running neither using your resources. It was a short-lived opt-in feature for some of our users who asked for a miner because they wanted to support but couldn't with our other avenues.
